package com.example.demo.entity;


import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@Entity
//@Data
//@Getter
//@Setter
//@NoArgsConstructor
//@AllArgsConstructor
public class ArticleSource {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private long article_id; //autogenerated ID
	private String title; //Title for the article
	private String img_url; // url for the image
	private String url; //actural url for redirection
	private String p_date; //publication date
	private long article_likes; //no_of_likes for the article
	private String article_source; // source from which the article is taken
	private String description; //description of the article(May be extended to paragraphs)
	private boolean isSaved = false; //variable for saved.
	public ArticleSource(long article_id, String title, String img_url, String url, String p_date, long article_likes,
			String article_source, String description, boolean isSaved) {
		super();
		this.article_id = article_id;
		this.title = title;
		this.img_url = img_url;
		this.url = url;
		this.p_date = p_date;
		this.article_likes = article_likes;
		this.article_source = article_source;
		this.description = description;
		this.isSaved = isSaved;
	}
	public ArticleSource() {
		super();
		// TODO Auto-generated constructor stub
	}
	public long getArticle_id() {
		return article_id;
	}
	public void setArticle_id(long article_id) {
		this.article_id = article_id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getImg_url() {
		return img_url;
	}
	public void setImg_url(String img_url) {
		this.img_url = img_url;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getP_date() {
		return p_date;
	}
	public void setP_date(String p_date) {
		this.p_date = p_date;
	}
	public long getArticle_likes() {
		return article_likes;
	}
	public void setArticle_likes(long article_likes) {
		this.article_likes = article_likes;
	}
	public String getArticle_source() {
		return article_source;
	}
	public void setArticle_source(String article_source) {
		this.article_source = article_source;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public boolean isSaved() {
		return isSaved;
	}
	public void setSaved(boolean isSaved) {
		this.isSaved = isSaved;
	}
	
	

}
