package com.example.demo.news;

import jakarta.persistence.*;

@Entity
@Table(name = "news_content")
public class NewsContent {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // autogenerated ID

    @Column(columnDefinition = "TEXT")
    private String content;

    // Constructors
    public NewsContent() {
    }

    public NewsContent(String content) {
        this.content = content;
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    // Equals and hashCode (optional, based on your needs)

    // toString (optional, for logging and debugging purposes)
    @Override
    public String toString() {
        return "NewsContent{" +
                "id=" + id +
                ", content='" + content + '\'' +
                '}';
    }
}

