package com.example.demo.news;

import jakarta.persistence.*;

@Entity
@Table(name = "news_url")
public class NewsUrl {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // autogenerated ID

    @Column(columnDefinition = "TEXT")
    private String url;

    // Constructors
    public NewsUrl() {
    }

    public NewsUrl(String url) {
        this.url = url;
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    // Equals and hashCode (optional, based on your needs)

    // toString (optional, for logging and debugging purposes)
    @Override
    public String toString() {
        return "NewsUrl{" +
                "id=" + id +
                ", url='" + url + '\'' +
                '}';
    }
}
