package com.example.demo.news;

import jakarta.persistence.*;

@Entity
@Table(name = "news_description")
public class NewsDescription {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // autogenerated ID

    @Column(columnDefinition = "TEXT")
    private String description;

    // Constructors
    public NewsDescription() {
    }

    public NewsDescription(String description) {
        this.description = description;
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    // Equals and hashCode (optional, based on your needs)

    // toString (optional, for logging and debugging purposes)
    @Override
    public String toString() {
        return "newsDescription{" +
                "id=" + id +
                ", description='" + description + '\'' +
                '}';
    }
}
