package com.example.demo.news;

import jakarta.persistence.*;

@Entity
@Table(name = "news_img")
public class NewsImage {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // autogenerated ID

    @Column(columnDefinition = "TEXT")
    private String imgUrl;

    // Constructors
    public NewsImage() {
    }

    public NewsImage(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    // Getters and setters
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getImgUrl() {
        return imgUrl;
    }

    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl;
    }

    // Equals and hashCode (optional, based on your needs)

    // toString (optional, for logging and debugging purposes)
    @Override
    public String toString() {
        return "NewsImage{" +
                "id=" + id +
                ", imgUrl='" + imgUrl + '\'' +
                '}';
    }
}
