package com.example.demo.news;

import jakarta.persistence.*;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "news_main")
public class NewsMain {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id; // autogenerated ID

    private String author;
    private String p_date;
    private long likes = 0;
    private boolean isSaved = false;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "description_id")
    private NewsDescription description;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "url_id")
    private NewsUrl url;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "img_id")
    private NewsImage img;

    @OneToOne(cascade = CascadeType.ALL)
    @JoinColumn(name = "content_id")
    private NewsContent content;

	public NewsMain(Long id, String author, String p_date, long likes, boolean isSaved, NewsDescription description,
			NewsUrl url, NewsImage img, NewsContent content) {
		super();
		this.id = id;
		this.author = author;
		this.p_date = p_date;
		this.likes = likes;
		this.isSaved = isSaved;
		this.description = description;
		this.url = url;
		this.img = img;
		this.content = content;
	}

	public NewsMain() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getAuthor() {
		return author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getP_date() {
		return p_date;
	}

	public void setP_date(String p_date) {
		this.p_date = p_date;
	}

	public long getLikes() {
		return likes;
	}

	public void setLikes(long likes) {
		this.likes = likes;
	}

	public boolean isSaved() {
		return isSaved;
	}

	public void setSaved(boolean isSaved) {
		this.isSaved = isSaved;
	}

	public NewsDescription getDescription() {
		return description;
	}

	public void setDescription(NewsDescription description) {
		this.description = description;
	}

	public NewsUrl getUrl() {
		return url;
	}

	public void setUrl(NewsUrl url) {
		this.url = url;
	}

	public NewsImage getImg() {
		return img;
	}

	public void setImg(NewsImage img) {
		this.img = img;
	}

	public NewsContent getContent() {
		return content;
	}

	public void setContent(NewsContent content) {
		this.content = content;
	}

    // Getters and setters

    // Constructors
    
}
