
package com.example.demo.entity;

//import jakarta.persistence.Column;
//import jakarta.persistence.Entity;
//import jakarta.persistence.GeneratedValue;
//import jakarta.persistence.GenerationType;
//import jakarta.persistence.Id;
//import jakarta.persistence.Lob;
import jakarta.persistence.*;

@Entity
@Table (name = "article_main")
public class ArticleDetails {
	@Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id; // autogenerated ID

    private String author;

    @Column(length = 1000) // Reduce the size based on your requirements
    private String title;

    @Column(length = 1000) // Use @Lob annotation for large text data
    private String description;

    @Column(length = 1000)// Use @Lob annotation for large text data
    private String url;

    @Column(length = 10000) // Use @Lob annotation for large text data
    private String img_url;

    private String p_date;

    @Column(length = 10000) // Use @Lob annotation for large text data
    private String content;

    private long likes = 0;
    private boolean isSaved = false;;

    public ArticleDetails() {

    }
    public ArticleDetails(Long id, String author, String title, String description, String url, String img_url,
            String p_date, String content, long likes, boolean isSaved) {
        this.id = id;
        this.author = author;
        this.title = title;
        this.description = description;
        this.url = url;
        this.img_url = img_url;
        this.p_date = p_date;
        this.content = content;
        this.likes = likes;
        this.isSaved = isSaved;
    }
    
    public Long getId() {
        return id;
    }
    public void setId(Long id) {
        this.id = id;
    }
    public String getAuthor() {
        return author;
    }
    public void setAuthor(String author) {
        this.author = author;
    }
    public String getTitle() {
        return title;
    }
    public void setTitle(String title) {
        this.title = title;
    }
    public String getDescription() {
        return description;
    }
    public void setDescription(String description) {
        this.description = description;
    }
    public String getUrl() {
        return url;
    }
    public void setUrl(String url) {
        this.url = url;
    }
    public String getImg_url() {
        return img_url;
    }
    public void setImg_url(String img_url) {
        this.img_url = img_url;
    }
    public String getP_date() {
        return p_date;
    }
    public void setP_date(String p_date) {
        this.p_date = p_date;
    }
    public String getContent() {
        return content;
    }
    public void setContent(String content) {
        this.content = content;
    }
    public long getLikes() {
        return likes;
    }
    public void setLikes(long likes) {
        this.likes = likes;
    }
    public boolean isSaved() {
        return isSaved;
    }
    public void setSaved(boolean isSaved) {
        this.isSaved = isSaved;
    }

    


    
}